### PR TITLE
Handle carry/borrow bit position

### PR DESCRIPTION
**Pull request by Mm7**
Handle carry/borrow bit position properly by ANDing operands

### CODE REVIEW

**Comment by Mm7** [comment]
Hi, @radare @sushant94 @ZhangZhuoSJTU please can you review this commit? Thank you.

**Comment by XVilka** [comment]
So far looks good. Waiting for one more opinion. @kriw @chinmaydd can you please take a look?
@Mm7 can you also please rebase it?

**Comment by Mm7** [comment]
@XVilka done.

**Comment by chinmaydd** [comment]
While we are in the process of minor refactoring, @Mm7 could you please improve existing debug statements? For example for: `lastsz unset!` maybe we can output the ESIL expression for which this condition was hit.

**Comment by Mm7** [comment]
Hi @chinmaydd I added a new error type: "UnknownOperandsSize". The following code should be able to catch these issues:
```
if let ParserError::UnknownOperandSize = parser.parse("some broken esil") {
   // handle the issue
}
```

**Comment by XVilka** [comment]
@kriw are you ok with this PR? Please check.

**Comment by kriw** [comment]
LGTM 👍

**Pull request merged**
